spring:
  application:
    name: Volunteer-Management-Module

  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui/index.html

  datasource:
    url: jdbc:mysql://localhost:3306/pulsedb
    username: root
    password: hemant
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
